version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: fenv-fvm
    main: ./cmd/fenv-fvm
    binary: fenv-fvm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: fenv-fvm
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  draft: false
  prerelease: auto
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - repository:
      owner: shunirr
      name: homebrew-fenv-fvm
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/shunirr/fenv-fvm"
    description: "FENV-compatible Flutter version management tool using FVM backend"
    license: "MIT"
    install: |
      bin.install "fenv-fvm"
    test: |
      system "#{bin}/fenv-fvm", "version"
